### PR TITLE
Multi period

### PR DESCRIPTION
**Pull request by maxaggedon**
I did this a while ago (and I use it). I was hoping to find time to clean a bit and add documentation on how to use, but did not get around to it yet. I would very much like to have some feedback on the api before I take the time to do it.

To test it:

```
<CalendarList
  markedDates={markedDates}
  markingType="multi-period"
/>
```

And here is a test sample of marked dates to use it with:

```
const markedDates = {
  "2017-11-28":{
    "periods":[
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#5f9ea0"
      }
    ]
  },
  "2017-11-29":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#5f9ea0"
      }
    ]
  },
  "2017-12-12":{
    "periods":[
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-13":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#f0e68c"
      },
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#ffa500"
      },
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#5f9ea0"
      }
    ]
  },
  "2017-12-14":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#5f9ea0"
      },
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#ffa500"
      },
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#5f9ea0"
      }
    ]
  },
  "2017-12-15":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#f0e68c"
      },
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#5f9ea0"
      },
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#ffa500"
      },
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#5f9ea0"
      },
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#ffa500"
      }
    ]
  },
  "2017-12-16":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#f0e68c"
      },
      {
        "color":"transparent"
      },
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#5f9ea0"
      },
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#ffa500"
      },
      {
        "color":"transparent"
      },
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#ffa500"
      }
    ]
  },
  "2017-12-17":{
    "periods":[
      {
        "color":"transparent"
      },
      {
        "color":"transparent"
      },
      {
        "color":"transparent"
      },
      {
        "color":"transparent"
      },
      {
        "color":"transparent"
      },
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#ffa500"
      }
    ]
  },
  "2017-12-18":{
    "periods":[
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-19":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-20":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-21":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-22":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-23":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-24":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-25":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":true,
        "endingDay":false,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-26":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-27":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":false,
        "color":"#f0e68c"
      },
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#f0e68c"
      },
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#f0e68c"
      }
    ]
  },
  "2017-12-28":{
    "periods":[
      {
        "startingDay":false,
        "endingDay":true,
        "color":"#f0e68c"
      }
    ]
  }
}
```

### CODE REVIEW

**Comment by tautvilas** [comment]
Hi, could you give an example image how your marking would look like? Also how is it different from period marking?

**Comment by maxaggedon** [comment]
Here is how it looks like !
screen shot 2018-03-26 at 11 15 03

**Comment by tautvilas** [comment]
Sweet :) Just few notes:

1) CI build is failing (check lint)
2) I'm not sure this will work proper with calendar-list because we don't support calendars of variable height in this component. When scrollTo(initialDate) is done, scroll position is calculated by fixed calendar height. But multiperiod can expand calendars

**Comment by tautvilas** [comment]
Hi, I think I will merge this. Could you update the readme and also add your marking demo to example project?

**Comment by maxaggedon** [comment]
Hi, sorry I haven't had the time to check on your second note about calendars fixed height... I remember I noticed it while I implemented the feature, but I don't have a solution for this right now.

I will update docs this week end or next week, and I will put a word of caution regarding usage with `<CalendarList />`.

**Comment by pennyandsean** [comment]
Hi, we have a use case for multi-period in the CalendarList, but don't have time right-now to take a look.  So we're putting our hand up as interested if someone does it, or we'll have a go at it some time in the near future.

**Pull request merged**
