### PR TITLE
Number localization

### PR DESCRIPTION
**Pull request by jesuscc1993**
Replacement for [#1079](https://github.com/wix/react-native-calendars/pull/1079), following the suggested alternative.

The way this works is by passing a `numbers` prop to the calendar components (e.g.: `["٠", "١", "٢", "٣", "٤", "٥", "٦", "٧", "٨", "٩"]`). It was discussed adding it to the LocaleConfig instead but this is defined by the XDate dependency so we can't change it.

### CODE REVIEW

**Review by jguix — APPROVED** [review]
Reviewed code and passed tests. I think this pull request is useful, well organized and follow conventions.

**Review by jguix — APPROVED** [review]
Reviewed code and passed tests. I think this pull request is useful, well organized and follow conventions.

**Comment by Inbal-Tish** [comment]
@jesuscc1993 Hi. I don't understand why we can't use LocaleConfig for that instead of holding a prop for the numbers array?

**Comment by jesuscc1993** [comment]
@Inbal-Tish LocaleConfig is a type declared by XDate, so we can't just add to it.
It would require extending it and replacing the type definition for all places that use LocaleConfig .

**Comment by Inbal-Tish** [comment]
@jesuscc1993 Look at 'app.js' where we define the 'LocalConfig' object in `LocaleConfig.locales['en']` line #23. Here we can add keys to the locale configuration on default 'en' and use it in the proper place (in this case, the Day component's Text). When the user wants to localize his app he will pass the other locales objects, as shown in the 'fr' example. In that object, he will pass the localized numbers array. See how I do it with the 'today' key.

**Comment by jesuscc1993** [comment]
@Inbal-Tish this is what I mean:
image

**Comment by Inbal-Tish** [comment]
@jesuscc1993 Do you get this error even when you defined the default 'en' local 'numbers' key in app.js? like so: 
`LocaleConfig.locales['en'] = {
  formatAccessibilityLabel: "dddd d 'of' MMMM 'of' yyyy",
  monthNames: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ],
  monthNamesShort: ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'],
  dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  dayNamesShort: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
  **numbers: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']**
};
`

**Comment by Inbal-Tish** [comment]
@jesuscc1993 By the way, I will do the formatting in the Day/index.js line #94 instead of having duplications in all Day components.

**Comment by jesuscc1993** [comment]
I see that the type definitions actually come from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-calendars) and not this library, so they shouldn't be relevant and your request should be doable.

I don't know when I'll be able to work on this PR, though. It's unlikely that it'll be soon.

I don't understand what you mean by this:
> I will do the formatting in the Day/index.js line #94 instead of having duplications in all Day components.

**Comment by Inbal-Tish** [comment]
@jesuscc1993 I meant that if you format the text in the Day/index component instead on the Day/basic/index component, we'll have in the Day/period/index as well

**Comment by jesuscc1993** [comment]
The PR has been reworked to meet your requests. Please, review at your earliest convenience.
@Inbal-Tish

**Review by Inbal-Tish — APPROVED** [review]

**Comment by Inbal-Tish** [comment]
@jesuscc1993 Greate job! Thank you so much!!

**Pull request merged**
