### PR TITLE
Update and fix example project and structure

### LINKED ISSUE #796: Example project moved to root?
What are the reasons for moving the example project into the root folder (11eeba61758e7e17decea80822a39a5bc4250e60), effectively mixing up the sample code with the library code? The usual setup for basically all React Native libraries is to have the example project(s) **fully contained** (and isolated) in a subfolder (conventionally `example`).

### LINKED ISSUE #900: Unable to resolve module `hoist-non-react-statics`...
Simulator Screen Shot - iPhone Xʀ - 2019-08-02 at 08 32 32

I run `npm install --save hoist-non-react-statics` to solve my problem. Just note that.

### PR DESCRIPTION
**Pull request by friederbluemle**
This PR is based on #997, and represents a **project structure** update and overhaul.

It cleanly separates example code from library code by moving all example related code (that includes the native folders `android/` and `ios/`) into the `example/` subdirectory. (Closes #796)

The example project now uses the latest version of `react-native-navigation` (4.3.0), and is properly **decoupled from the library code** in the root.

Fixes #900, supersedes and closes #963

Successfully verified and tested on:
- Android Device (Xiaomi Mi A2)
- Android Emulator (Pixel 3a)
- iOS Device (iPhone 8)
- iOS Simulator (iPhone 11)

<p align="center">
 
</p>

<p align="center">
 
</p>

@tautvilas @Inbal-Tish @ethanshar @ButtersHub Please review.

Also, a quick question about `pom.xml`: This file was first added in 2016, and then modified once by @ButtersHub last year (see a88b4f8b833150234ce95b01d49cb35c89f1923a). Does anyone know the purpose of this file? Is it used anywhere? As you might know, this file is normally related to the Maven build system, and is very uncommon in React Native.

Thank you!

### CODE REVIEW

**Comment by friederbluemle** [comment]
Rebased and fixed conflict.

@Inbal-Tish - Please review 🙏

**Comment by Inbal-Tish** [comment]
@friederbluemle Hi. First, thank you for your contribution! 
As a general note, you're mixing too many things under one PR which makes it harder to review. Please separate to different PRs with a description for each - what is the issue you're trying to solve and what is your solution. 
Second, you have here changes you submitted in PR #997, so you make your own duplications... 
And last, changing a project structure is a big deal, please submit your solution in a clean and clear way. 
Thanks again!

**Comment by friederbluemle** [comment]
Hi @Inbal-Tish - Thanks for getting back to me!
I'd be happy to submit several PRs, if you advise how you would like this to be broken down.
As I explained in the PR description, this branch is _based_ on the branch in #997 (which should be merged first). After that, I will rebase the branch here, removing two commits. I can further break it down if you want.

**Comment by Inbal-Tish** [comment]
Hi. As I was saying, it's not advisable to rely on another PR, that may or may not be merged, it will only block the current PR. If you made changes that require other changes, submit all on the same PR.
Second, each PR should include only the changes for the issue it tackles, without mixing other issues. That's for the same reason, it might get blocked only because one issue will not be accepted while another might be merged otherwise.

**Comment by friederbluemle** [comment]
@Inbal-Tish - Sure thing, I've excluded the commits related to npmignore update and Lint fixes. With this, `yarn lint` will fail in the example project, but we can fix it in a follow-up PR.

**Comment by friederbluemle** [comment]
Also, please let me know if you prefer me to close #997 and squash all commits into this one here.
Since you stated correctly that PRs should not mix things that are not related, it would be nice to get #997 merged first - it has _zero_ dependencies on the changes in this PR.
Thanks!

**Comment by Inbal-Tish** [comment]
Again, if this PR has no dependency on PR #997 then don't include its changes but only the relevant changes for this PR. If you add the changes from PR #997 they might block this PR as the changes in it may or may not be merged at all. 
And, as I was saying before, this PR has too many issues all in one. You should separate them to different PRs.

**Comment by jainmnsh** [comment]
Hello, I am must be doing something wrong  but I tried to download the branch and did the following in the example folder.
npm install
react-native run-ios


 ~/workspaces/jss/test/react-native-calendars/example/ [update-project] react-native run-ios --verbose
debug Reading /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Podfile
debug Reading /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Podfile.lock
info Found Xcode workspace "CalendarsExample.xcworkspace"
info Building (using "xcodebuild -workspace CalendarsExample.xcworkspace -configuration Debug -scheme CalendarsExample -destination id=693FBD31-86FC-4412-8661-BCA9DB541E0D -derivedDataPath build/CalendarsExample")
debug User defaults from command line:
    IDEDerivedDataPathOverride = /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/build/CalendarsExample

Build settings from command line:
    TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault


debug note: Using new build system

debug note: Planning build

debug note: Constructing build description

debug error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExample/Pods-CalendarsExample.debug.xcconfig: unable to open file (in target "CalendarsExample" in project "CalendarsExample") (in target 'CalendarsExample' from project 'CalendarsExample')

debug error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExample/Pods-CalendarsExample.debug.xcconfig: unable to open file (in target "CalendarsExample" in project "CalendarsExample") (in target 'CalendarsExample' from project 'CalendarsExample')
error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExample/Pods-CalendarsExample.debug.xcconfig: unable to open file (in target "CalendarsExample" in project "CalendarsExample") (in target 'CalendarsExample' from project 'CalendarsExample')

debug error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExample/Pods-CalendarsExample.debug.xcconfig: unable to open file (in target "CalendarsExample" in project "CalendarsExample") (in target 'CalendarsExample' from project 'CalendarsExample')

debug error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExampleTests/Pods-CalendarsExampleTests.debug.xcconfig: unable to open file (in target "CalendarsExampleTests" in project "CalendarsExample") (in target 'CalendarsExampleTests' from project 'CalendarsExample')

debug error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExampleTests/Pods-CalendarsExampleTests.debug.xcconfig: unable to open file (in target "CalendarsExampleTests" in project "CalendarsExample") (in target 'CalendarsExampleTests' from project 'CalendarsExample')

debug error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExampleTests/Pods-CalendarsExampleTests.debug.xcconfig: unable to open file (in target "CalendarsExampleTests" in project "CalendarsExample") (in target 'CalendarsExampleTests' from project 'CalendarsExample')

debug error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExampleTests/Pods-CalendarsExampleTests.debug.xcconfig: unable to open file (in target "CalendarsExampleTests" in project "CalendarsExample") (in target 'CalendarsExampleTests' from project 'CalendarsExample')

debug 


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening CalendarsExample.xcworkspace.
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/build/CalendarsExample

Build settings from command line:
    TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault

note: Using new build system
note: Planning build
note: Constructing build description
error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExample/Pods-CalendarsExample.debug.xcconfig: unable to open file (in target "CalendarsExample" in project "CalendarsExample") (in target 'CalendarsExample' from project 'CalendarsExample')
error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExample/Pods-CalendarsExample.debug.xcconfig: unable to open file (in target "CalendarsExample" in project "CalendarsExample") (in target 'CalendarsExample' from project 'CalendarsExample')
error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExample/Pods-CalendarsExample.debug.xcconfig: unable to open file (in target "CalendarsExample" in project "CalendarsExample") (in target 'CalendarsExample' from project 'CalendarsExample')
error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExample/Pods-CalendarsExample.debug.xcconfig: unable to open file (in target "CalendarsExample" in project "CalendarsExample") (in target 'CalendarsExample' from project 'CalendarsExample')
error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExampleTests/Pods-CalendarsExampleTests.debug.xcconfig: unable to open file (in target "CalendarsExampleTests" in project "CalendarsExample") (in target 'CalendarsExampleTests' from project 'CalendarsExample')
error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExampleTests/Pods-CalendarsExampleTests.debug.xcconfig: unable to open file (in target "CalendarsExampleTests" in project "CalendarsExample") (in target 'CalendarsExampleTests' from project 'CalendarsExample')
error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExampleTests/Pods-CalendarsExampleTests.debug.xcconfig: unable to open file (in target "CalendarsExampleTests" in project "CalendarsExample") (in target 'CalendarsExampleTests' from project 'CalendarsExample')
error: /Users/mjain/workspaces/jss/test/react-native-calendars/example/ios/Pods/Target Support Files/Pods-CalendarsExampleTests/Pods-CalendarsExampleTests.debug.xcconfig: unable to open file (in target "CalendarsExampleTests" in project "CalendarsExample") (in target 'CalendarsExampleTests' from project 'CalendarsExample')


** BUILD FAILED **

**Comment by friederbluemle** [comment]
Hi @jainmnsh - Just like any other React Native (0.60+) project, these are the steps to run the app on iOS:

_Within_ the `example/` subfolder:

1. `yarn`
2. `pushd ios && pod install && popd`
3. `yarn ios`

This example app will start up.
All this assumes that you have other general React Native prerequisites checked off (e.g. CocoaPods). See https://facebook.github.io/react-native/docs/getting-started

**Comment by jainmnsh** [comment]
thank @friederbluemle  - appreciate it -

**Comment by vmurillo** [comment]
> Hi @jainmnsh - Just like any other React Native (0.60+) project, these are the steps to run the app on iOS:
> 
> _Within_ the `example/` subfolder:
> 
> 1. `yarn`
> 2. `pushd ios && pod install && popd`
> 3. `yarn ios`
> 
> This example app will start up.
> All this assumes that you have other general React Native prerequisites checked off (e.g. CocoaPods). See https://facebook.github.io/react-native/docs/getting-started

In the current master branch(now), there is no ios directory in example.

**Pull request closed without merging**
