### PR TITLE
Make multi-dot strategy to respect provided selectedColor

### PR DESCRIPTION
**Pull request by pinguinjkeke**
```selectedColor``` in the multi-dot section inside README.md is not working and not logically correct because code cannot decide which dot ```selectedColor``` property would be applied if we have multiple dots on one day.

This PR moved ```selectedColor``` one level up (look README.md commit) and adds missing functionality.
I'm using it in my project. It would be cool if you merge this.

### CODE REVIEW

**Comment by tautvilas** [comment]
Hi,  as I understand currently selectedColor for dots works correctly - this setting means what color to change the dot color to when the day is selected. So it makes sense that it is specified per/dot. What you want to do is probably to have ability to change selected day (not dot) color. Can you improve your PR to address only this usecase?

**Comment by pinguinjkeke** [comment]
https://github.com/pinguinjkeke/react-native-calendars/blob/3d672fa0aa4b8a48fa74660a736ca04149a71e25/src/calendar/day/multi-dot/index.js#L69

There is wrong name. Not ```selectedColor``` but ```selectedDotColor``` for dots. So it's a mispell inside README.md. I can rename ```selectedColor``` to ```selectedDotColor``` inside README.md.

Will it be ok?

**Comment by tautvilas** [comment]
You're right. Yes if you could fix this mistake in Readme would be great. Also I saw that there is such mistake in example project where multidot is used, could you add a naming fix there too?

**Comment by pinguinjkeke** [comment]
It's all fixed now

**Comment by tautvilas** [comment]
Thanks!

**Pull request merged**
