### PR TITLE
moment js as an optional dependency

### PR DESCRIPTION
**Pull request by radekrepka**
Moment.js is a legacy project in maintenance mode now and this repo use xdate library for dates.

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@radekrepka I love this PR! I'm all in favor of removing 'moment'.
One issue though: removing `useMoment` from AgendaList is a breaking change. So we can do it in V2 or make 'moment' an optional dependency till then. What do you think?

**Comment by NS-BOBBY-C** [comment]
Could this include an option to keep moment? I'm not sure what happens under the hood, but I can see people still wanting to use moment (namely, me! :)).

**Comment by Inbal-Tish** [comment]
> Could this include an option to keep moment? I'm not sure what happens under the hood, but I can see people still wanting to use moment (namely, me! :)).

Are you using `useMoment` prop or passing a moment date object?

**Comment by radekrepka** [comment]
okey, moment is an optional dependency now

**Review by Inbal-Tish — APPROVED** [review]

**Pull request merged**
