### PR TITLE
change lodash import way to make more tree-shakeable

### PR DESCRIPTION
**Pull request by xsbchen**
webpack can not remove unuse methods in lodash, because we use `require('lodash')` to import it
so change to `require('lodash/methodX')`

### CODE REVIEW

**Comment by xsbchen** [comment]
@ethanshar @Inbal-Tish Could you help me to review this PR? Please.

**Review by ethanshar — APPROVED** [review]

**Comment by ethanshar** [comment]
@Inbal-Tish 
Looks good to me, I approved. 
Leaving you to merge

**Comment by Inbal-Tish** [comment]
@xsbchen One question: why can't we extract the methods this way `import {invoke, isFunction} from 'lodash';` instead of having two lines of imports in this case?

**Comment by xsbchen** [comment]
> @xsbchen One question: why can't we extract the methods this way `import {invoke, isFunction} from 'lodash';` instead of having two lines of imports in this case?

No, lodash did not support this way for tree-shaking

**Pull request merged**
