### PR TITLE
Agenda - fix keyExtractor for reservation list

### PR DESCRIPTION
**Pull request by Inbal-Tish**
Agenda - fix `keyExtractor` for reservation list and allow passing a custom one

### CODE REVIEW

**Review by lidord-wix — APPROVED** [review]

**Comment by eladgel** [comment]
@lidord-wix @Inbal-Tish this does not fix the issue as the declared keyExtractor in your solution propagates to the CalendarList instead of the agenda. We use the same property for both lists!!

**Comment by Inbal-Tish** [comment]
@eladgel Thank you! I pushed a fix for the prop name

**Comment by eladgel** [comment]
@Inbal-Tish Any ETA on when is **1.12789.0** coming out?

**Comment by Inbal-Tish** [comment]
> @Inbal-Tish Any ETA on when is **1.12789.0** coming out?

We're usually releasing a version every two weeks, so begging of March should be the next version.

**Comment by prabir-vora** [comment]
Can someone post an example of how to use the keyExtractor with Agenda? I am facing the same issue with updating the items in Agenda and incorrect items displaying. I am hoping using keyExtractor fixes it so if someone can guide me on how to use it that would be very helpful.

**Comment by juspeeh** [comment]
I don't understand how keyExtractor should be used either. It's just returning XDate for each month I have set for scrollRange. How is that supposed to help me separate items from each other?

**Comment by prabir-vora** [comment]
@juspeeh If it helps, in my case I went inside the node_modules and in the Reservations List component, I added my own implementation of keyExtractor. I believe the **reservationKeyExtractor** is the prop they expect for your own implementation but it wasn't getting called for me.

**Comment by juspeeh** [comment]
Yep it's not getting called. reservationsKeyExtractor is always undefined even tho you pass it to the Agenda. Noticed that keyExtractor has fallback  ``${item?.reservation?.day}${index}`;` which I'm able to use for the purpose. I just generate random string for every single object to day property. Now it seems to be working. 

@prabir-vora Thanks for reaching back.

Why are these things not documented?

Completely breaks the whole calendar to a state where it cannot be used unless you start debugging the library and find these things yourself.

**Comment by Inbal-Tish** [comment]
Hi all. Bug fixed (will be released on the next version). You can now use `<Agenda ... reservationsKeyExtractor={yourKeyExtractor}/>`

**Comment by gkasireddy202** [comment]
I still getting this issue in the latest version.
Any updates?

**Pull request merged**
