### PR TITLE
Horizontal scroll on CalendarList

### LINKED ISSUE #90: Horizontal scrolling?
Is it possible to add a prop in the listview for calendarlist to scroll horizontally instead of vertically?

### PR DESCRIPTION
**Pull request by tigo0**
## Description
This PR is improvement for CalendarList that adds horizontally scrolled calendar and pagination. 
Fixes #90 

## What changed
Added props for CalendarList, namely `pagingEnabled`, `horizontal` and `calendarWidth`. `PagingEnabled` is disabled if `calendarWidth` is set.

### CODE REVIEW

**Comment by tautvilas** [comment]
Hello, thanks for PR, could add a horizontal calendar example to example project and update Readme?

**Comment by tigo0** [comment]
Hey @tautvilas, I will make a new PR with this change since this one follows the git history of my other PR's in this project. Or is this fine? Example and Readme update will follow shortly.

**Comment by tautvilas** [comment]
If you need make new PR so that we would have a clean PR

**Comment by tigo0** [comment]
Closing this one in favor of another one that will follow.

**Pull request closed without merging**
