### PR TITLE
Add support for dots on period style

### PR DESCRIPTION
**Pull request by ovbm**
This PR adds the ability to have dots and periods in the same calendar:
Screenshot 2020-05-03 at 16 13 36

### CODE REVIEW

**Comment by borasumer** [comment]
no one is reviewing ?

**Comment by ovbm** [comment]
it doesn't look like they have the capacity to maintain this anymore, which is a shame.

**Comment by dragslag** [comment]
@ovbm thank you for this, which marking type do I use now?

**Comment by ovbm** [comment]
Hi, use `markingType="period"`

**Comment by dragslag** [comment]
> Hi, use `markingType="period"`

THANK YOU, it works!!

**Comment by chenei** [comment]
Hi @ovbm ,
Sorry I didn’t see this PR.
We just start to maintain this library again and I am trying to closing the gaps.
This feature already implemented, please check the docs.

**Comment by ovbm** [comment]
Well at least it's supported now. thanks for maintaining it!

**Pull request closed without merging**
