### PR TITLE
Add styling customization options

### PR DESCRIPTION
**Pull request by asantos00**
This PR adds a few styling customisation options as well as some minor fixes.

However, in the future (maybe in a new version, cause it's a breaking change) it would be cool to have a more structured way of styling each component so we can allow full customisation of the styles while keeping a default.

Example:

```
const headerStyle = {
  // all the header styles,
  ...appStyle.header
}

const dayStyle = {
  // all the day styles,
  ...appStyle.day
}
```

This way it would be easy for the user to change whatever we wants regarding styles (instead of just some props that we keep adding so we can customize) and we can even use the "normal" stylesheet api, instead of names like `textSectionTitleColor` it turns out even harder to use and document.

### CODE REVIEW

**Comment by tautvilas** [comment]
Hi, please check out #100 discussion about styling

**Comment by tautvilas** [comment]
resolved using stylesheets ovveride https://github.com/wix/react-native-calendars#advanced-styling

**Comment by asantos00** [comment]
Sorry If I'm mistaken, but when you use stylesheets override doesn't that overrides the styles defined on the markedDates?

**Comment by tautvilas** [comment]
hey, could you give an example?

**Comment by asantos00** [comment]
Hey

Imagine that I define the color of the selected days by using this theme override you talked about, can I override that selected days color in my `markedDates` object? (that happens when I want to have multiple selected periods with different colors)

**Pull request closed without merging**
