### PR TITLE
Adding defaultDayMark

### PR DESCRIPTION
**Pull request by chenei**

### CODE REVIEW

**Comment by chenei** [comment]
I also refactored the example file so we can comment easily examples.

**Comment by chenei** [comment]
resolves #1095

**Comment by ethanshar** [comment]
Before I dive in into this one. 
I meant that the `defaultDayMark` prop will be an **object** specifying the default marking options for all days. 
But maybe I misunderstood the requirement :/

**Comment by Inbal-Tish** [comment]
@chenei Can you please add a description.

**Comment by emilisb** [comment]
@chenei any plans to finish with this?

**Pull request closed without merging**
