### PR TITLE
Support passing right spacing for overlapping Timeline events

### PR DESCRIPTION
**Pull request by ethanshar**
First of all, I refactored the Packer util for Timeline component. 
I mainly changed some function names, fixed typings and add some comments to explain the code (the part of code is very not intuitive) 

Also, I added support for injecting options to the Packer util and specifically in this PR added support to pass a custom right spacing between overlapping events.

### CODE REVIEW

**Review by lidord-wix — COMMENTED** [review]
Looks good overall, but I think we should have a prop called `spaceBetweenOverlappedEvents` for example, that will be applied between overlapped events and not for all the events (because `eventRightSpacing` applied to all the events).

**Comment by ethanshar** [comment]
> Looks good overall, but I think we should have a prop called `spaceBetweenOverlappedEvents` for example, that will be applied between overlapped events and not for all the events (because `eventRightSpacing` applied to all the events).

You mean that the name (`eventRightSpacing`) hints that it applies to all events?

**Comment by lidord-wix** [comment]
> > Looks good overall, but I think we should have a prop called `spaceBetweenOverlappedEvents` for example, that will be applied between overlapped events and not for all the events (because `eventRightSpacing` applied to all the events).
> 
> You mean that the name (`eventRightSpacing`) hints that it applies to all events?

Yes, and it does apply to events. but we should also provide a way to control only the space between overlapped events

**Comment by ethanshar** [comment]
> > > Looks good overall, but I think we should have a prop called `spaceBetweenOverlappedEvents` for example, that will be applied between overlapped events and not for all the events (because `eventRightSpacing` applied to all the events).
> > 
> > 
> > You mean that the name (`eventRightSpacing`) hints that it applies to all events?
> 
> Yes, and it does apply to events. but we should also provide a way to control only the space between overlapped events

Ok, I fixed it. 
Not overlapping event don't get this spacing and I renamed to `overlapEventsSpacings`

**Review by lidord-wix — APPROVED** [review]

**Pull request merged**
