### PR TITLE
Convert ListView to FlatList

### LINKED ISSUE #42: Use FlatList instead of ListView
did you consider using FlatList instead of ListView?

### PR DESCRIPTION
**Pull request by jkomyno**
Fixes #42. Tested both in production (in a private app) and in the example. Updated README with new prop keyExtractor in Agenda.js.

### CODE REVIEW

**Comment by sibelius** [comment]
can you remove examples from this PR? this will make simpler to review

**Comment by jkomyno** [comment]
@sibelius: in my PR https://github.com/wix/react-native-calendars/pull/109 @tautvilas suggested that the example stuff should be merged soon.

Unfortunately I created the separate branch `feature/flatlist` without realizing that it also had the example refactoring in the Git history. Sorry for that, I guess it may be annoying for the mantainers

**Comment by skoob13** [comment]
Seems like CalendarList component doesn't work at all. Issue is probably hidden in **visibleRowsChange** and **onScroll** methods (ListView's onChangeVisibleRows has a different notation than FlatList).

**Comment by AbdallaMohamed** [comment]
How is this coming along? I'm interested in the performance gains this will achieve

**Comment by tautvilas** [comment]
Hey thanks for PR, but I did my own implementation

**Pull request closed without merging**
