### PR TITLE
Added missed calendarHeight props to Agenda

### PR DESCRIPTION
**Pull request by IronTony**
Added missed calendarHeight props to Agenda so we can use:
`
<Agenda
    calendarHeight={480}
/>
`
to customize the height of the Calendar

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@IronTony Hi. Please submit PRs that are not based on one another, so I can review the relevant changes for each one. Also, please resolve the conflicts. Thanks

**Comment by IronTony** [comment]
@Inbal-Tish Hi. Do you refer to the duplicate of the other one? I did the PR because I did the code fix. I never copied or something similar. I checked the other PR and mine had been opened the 18 Mar 2019 and the other had been opened the 30 Oct 2019. So I really don't remember and don't know what happened.

**Comment by IronTony** [comment]
@Inbal-Tish About this one I will fix the conflicts. Thx

**Comment by Inbal-Tish** [comment]
@IronTony What I mean is that this PR is about adding `calendarHeight` to the Agenda so let's keep it clean and not rely on another PR, that may or may not be merged, and only blocks this PR.
Let's converse on the other one in its own board. 
Waiting for your fixes, thank you!

**Pull request closed without merging**
