### PR TITLE
Support for multiple marker dots in Calendar and CalendarList

### PR DESCRIPTION
**Pull request by jaruyot**
Related to issue #137 

Added support for multiple dots for simple marking type in Calendar and CalendarList. Updated documentation in README.md.

Example:

<kbd>
  
</kbd>

```javascript
const vacation = {key='vacation', color: 'red', selectedColor: 'blue'};
const massage = {key='massage', color: 'blue', selectedColor: 'blue'};
const workout = {key='workout', color: 'green'};

<Calendar
  markedDates={{
    '2017-10-25': {dots: [vacation, massage, workout]},
    '2017-10-26': {dots: [massage, workout},
  }},
  markingType={'multi-dot'}
/>
```

### CODE REVIEW

**Comment by tautvilas** [comment]
Hey, thanks for PR, could you try implementing this as a new marking type? Thank means you would have to add new folder /calendar/day/multi-dot. The api to use your marking type should be:

```
const vacation = {color: 'red', selectedColor: 'blue'};
const massage = {color: 'blue', selectedColor: 'blue'};
const workout = {color: 'green', selectedColor: 'blue'};
<Calendar
  markedDates={{
    '2017-10-25': {dots: [vacation,massage,workout], disabled: true},
    '2017-10-26': {dots: [vacation,massage], disabled: false},
  }},
  markingType={'multi-dot'}
/>
```

This way you would have ownership of your marking type and will be able to maintain it. You can choose how your marking type will be called :) If there are questions, please do not hesitate to ask.

**Comment by jaruyot** [comment]
Thanks for your suggestion @tautvilas. I've created a new 'multi-dot' marking type and placed the day code in src/calendar/day/multi-dot.

**Comment by tautvilas** [comment]
Thanks, I will review this probably next week

**Comment by rameshvishnoi90904** [comment]
Is this committed ?

**Comment by tautvilas** [comment]
Not merged yet, will review this week

**Comment by rameshvishnoi90904** [comment]
Thanks, for replying
@tautvilas

**Comment by tautvilas** [comment]
merged @jaruyot . now this marking will be available in 1.9.0. But why do we need key prop? without it marking does not work

**Comment by jgcmarins** [comment]
Good job!

**Comment by jaruyot** [comment]
Thanks @tautvilas. I made key mandatory because otherwise you'd get a warning shown below. Using key is recommended when you render an array of elements as described in https://reactjs.org/docs/lists-and-keys.html#keys

Perhaps we should make key optional and show the warning so that it's clear that key is missing?

image

**Comment by tautvilas** [comment]
hey, you can generate key using array index and then there would be no warning

**Comment by maxaggedon** [comment]
Hey, I'd like to continue this discussion because I ran into a simple issue. In the example from the docs:
```
const vacation = {key:'vacation', color: 'red', selectedColor: 'blue'};
const massage = {key:'massage', color: 'blue', selectedColor: 'blue'};
const workout = {key:'workout', color: 'green'};

<Calendar
  markedDates={{
    '2017-10-25': {dots: [vacation, massage, workout], selected: true},
    '2017-10-26': {dots: [massage, workout], disabled: true},
  }},
  markingType={'multi-dot'}
/>
```
let's say I want to mark one day twice with the same event type (represented by a dot), then I just put it twice, like that: 
```
 '2017-10-26': {dots: [workout, massage, workout], disabled: true},
```
but this will generate a warning because several items have the same `key`. If the key was generated like @tautvilas suggested, this would not be a problem.

**Comment by jaruyot** [comment]
@maxaggedon Thanks for the comment. I've submitted pull request #324 to make key property optional. If you omit key then the array index will be used as key instead. 

Code sample:
```
const vacation = {color: 'red', selectedColor: 'blue'};
const massage = {color: 'blue', selectedColor: 'blue'};
const workout = {color: 'green'};
```

**Comment by mkekovic** [comment]
Does anyone know if we can make this dynamic? Such as populating the object from database that can be then passed into the markedDates prop.

**Pull request merged**
