### PR TITLE
Moved react and react-native to peerDependencies

### LINKED ISSUE #1530: Upgrade to React Native 0.64.x
## Description

`tsc` errors when using React Native 0.64.2

## Expected Behavior

no errors

## Observed Behavior

type errors in VSCode and when running `tsc`

many many many, but here's a representative sample:

```
error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Pick<Pick<ViewProps & RefAttributes<View>, "ref" | "style" | "hitSlop" | "onLayout" | "testID" | "hasTVPreferredFocus" | "tvParallaxProperties" | ... 48 more ... | "key"> & Partial<...>, "ref" | ... 54 more ... | "key"> & { ...; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type 'import("/Users/.../node_modules/@types/react-native/index").StyleProp<import("/Users/.../node_modules/@types/react-native/index").ViewStyle>' is not assignable to type 'import("/Users/.../node_modules/@types/react-native-calendars/node_modules/@types/react-native/index").StyleProp<import("/Users/.../node_modules/@types/react-native-calendars/node_modules/@types/react-native/index").ViewStyle>'.
      Type 'ViewStyle' is not assignable to type 'StyleProp<ViewStyle>'.
        Type 'import("/Users/.../node_modules/@types/react-native/index").ViewStyle' is not assignable to type 'import("/Users/.../node_modules/@types/react-native-calendars/node_modules/@types/react-native/index").ViewStyle'.
  Overload 2 of 2, '(props: StyledComponentPropsWithAs<typeof View, DefaultTheme, {}, never, typeof View, typeof View>): ReactElement<StyledComponentPropsWithAs<typeof View, DefaultTheme, {}, never, typeof View, typeof View>, string | ... 1 more ... | (new (props: any) => Component<...>)>', gave the following error.
    Type 'import("/Users/.../node_modules/@types/react-native/index").StyleProp<import("/Users/.../node_modules/@types/react-native/index").ViewStyle>' is not assignable to type 'import("/Users/.../node_modules/@types/react-native-calendars/node_modules/@types/react-native/index").StyleProp<import("/Users/.../node_modules/@types/react-native-calendars/node_modules/@types/react-native/index").ViewStyle>'.
      Type 'ViewStyle' is not assignable to type 'StyleProp<ViewStyle>'.
        Type 'import("/Users/.../node_modules/@types/react-native/index").ViewStyle' is not assignable to type 'import("/Users/.../node_modules/@types/react-native-calendars/node_modules/@types/react-native/index").ViewStyle'.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `yarn list react-native-calendars`: react-native-calendars@1.1263.0
* `yarn list react-native`: react-native@0.64.2

Also specify:

1. Phone/emulator/simulator & version: physical android 11

## Reproducible Demo

N/A

### PR DESCRIPTION
**Pull request by alessiocancian**
Should fix #1530

### CODE REVIEW

**Comment by alessiocancian** [comment]
So the problem here is that ci bot need to install `react` and `react-native` to run tests, but peerDependencies aren't installed automatically.
I don't know if there's a way to tell jenkins to install them...

**Comment by Inbal-Tish** [comment]
@alessiocancian Hi. Thank you for the PR. Regarding your code, you can't remove 'react' and 'react-native' from `devDependencies` - the lib needs them for development. The `peerDependencies` is what the app installing the lib will need to have installed. Also, these versions should be the minimum versions for the peer as it uses apis that might not be available in older versions.

**Comment by a613** [comment]
@Inbal-Tish is there a better PR

**Comment by Inbal-Tish** [comment]
@alessiocancian is  #1590 not resolving issue  #1530? If you wish to move "react" and  "react-native" to peerDependencies you need to add them to devDependencies as well.

**Comment by alessiocancian** [comment]
> @alessiocancian is #1590 not resolving issue #1530? If you wish to move "react" and "react-native" to peerDependencies you need to add them to devDependencies as well

> 

What I was suggesting is that the library shouldn't have it's own dependencies to react and react-native but use the installed version in the project, and you achieve this by using peerDependencies.
Otherwise issues like #1530 will happen again with future releases, or if someone uses older version of react-native.

So my advice is that a library should have react and react-native (or react-dom if that's the case) only as peerDependencies, the problem here was that CI needs to install them to build for tests, you should have an example project for testing and put the dependencies there.

**Pull request closed without merging**
