### PR TITLE
Agenda closed by default

### PR DESCRIPTION
**Pull request by IronTony**
Added a props on the Agenda to load it closed.
Based on this comment and code: https://github.com/wix/react-native-calendars/issues/309#issuecomment-375109475

### CODE REVIEW

**Comment by tannermares** [comment]
I'd love to use this! Is there anything blocking this being merged?

**Comment by budo60** [comment]
+1 i need this too, good improvements

**Comment by anagar23** [comment]
Is it merged in Master yet ?

**Comment by IronTony** [comment]
No, not yet 😞

**Pull request closed without merging**
