### PR TITLE
Fix/theme issues

### PR DESCRIPTION
**Pull request by dlariosuniandes**
Reverted props extraction as they seem to mess with the Theme for the Agenda

### CODE REVIEW

**Comment by dlariosuniandes** [comment]
Hi is there any way I can test this build ?

**Comment by bakwas247** [comment]
Yeah, if you compile the files using "tsc", then use the newly emitted files as a node module, you can test it. They also already have a set of tests prepared, that the docs tell you how to run.

**Comment by Inbal-Tish** [comment]
@dlariosuniandes Please describe the bug you wish to solve. Reverting to the previous usage of `extractComponentProps` is not recommended for performance. We'll need to find how to fix `extractHeaderProps` instead, so please add a description of the bug and a code snippet so we can try to reproduce it.

**Comment by Saikedo** [comment]
Are there any plans to address this ? Currently it is impossible to modify a lot of the Theme props for the agenda.

**Comment by Inbal-Tish** [comment]
@Saikedo Hi. See the PR #2041

**Comment by Saikedo** [comment]
@Inbal-Tish Seems like `backgroundColor` is still not working after the PR #2041.

I managed to make it work with `reservationsBackgroundColor` but I am not sure if this is appropriate since `reservationsBackgroundColor` is not even listed in the Theme.

Am I missing something? Is there a better way of handling this?

**Pull request closed without merging**
