### PR TITLE
Fix scrollToDay and scrollToMonth in CalendarList when horizontal

### PR DESCRIPTION
**Pull request by christophehurpeau**

### CODE REVIEW

**Comment by tautvilas** [comment]
@tigo0  plz review

**Comment by tautvilas** [comment]
@christophehurpeau could you explain what was the bug? thanks

**Comment by christophehurpeau** [comment]
With the horizontal mode enabled, without this the height is used to calculate the scroll offset, so unless the height is the same than the width it doesn't work.
Let's say you have a width of 500 and a height of 400. You are on month 1 and want to scroll to month 2: without the fix, the offset is set to 400 and you will end up beetween the month 1 and 2

**Comment by tautvilas** [comment]
thanks

**Pull request merged**
