### PR TITLE
FEAT: Added a way to set current month to be shown on Calendar.

### PR DESCRIPTION
**Pull request by vinodgrab**
Added an ability to load calendar for selected month

### CODE REVIEW

**Comment by tautvilas** [comment]
hi, what was wrong with using props.current?

**Comment by vinodgrab** [comment]
I think then there is no way to set today’s date.


Sent from my iPhone

> On 12-Jan-2018, at 5:29 PM, Tautvilas Mečinskas <notifications@github.com> wrote:
> 
> hi, what was wrong with using props.current?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
*Grab is hiring. Learn more at **https://grab.careers 
<https://grab.careers/>*

By communicating with Grab Inc and/or its subsidiaries, associate companies 
and jointly controlled entities (“Grab Group”), you are deemed to have 
consented to processing of your personal data as set out in the Privacy 
Notice which can be viewed at https://grab.com/privacy/

This email contains confidential information and is only for the intended 
recipient(s). If you are not the intended recipient(s), please do not 
disseminate, distribute or copy this email and notify Grab Group 
immediately if you have received this by mistake and delete this email from 
your system. Email transmission cannot be guaranteed to be secure or 
error-free as any information therein could be intercepted, corrupted, 
lost, destroyed, delayed or incomplete, or contain viruses. Grab Group do 
not accept liability for any errors or omissions in the contents of this 
email arises as a result of email transmission. All intellectual property 
rights in this email and attachments therein shall remain vested in Grab 
Group, unless otherwise provided by law.

**Comment by vinodgrab** [comment]
Can you please get this merged 

Sent from my iPhone

> On 12-Jan-2018, at 5:29 PM, Tautvilas Mečinskas <notifications@github.com> wrote:
> 
> hi, what was wrong with using props.current?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
*Grab is hiring. Learn more at **https://grab.careers 
<https://grab.careers/>*

By communicating with Grab Inc and/or its subsidiaries, associate companies 
and jointly controlled entities (“Grab Group”), you are deemed to have 
consented to processing of your personal data as set out in the Privacy 
Notice which can be viewed at https://grab.com/privacy/

This email contains confidential information and is only for the intended 
recipient(s). If you are not the intended recipient(s), please do not 
disseminate, distribute or copy this email and notify Grab Group 
immediately if you have received this by mistake and delete this email from 
your system. Email transmission cannot be guaranteed to be secure or 
error-free as any information therein could be intercepted, corrupted, 
lost, destroyed, delayed or incomplete, or contain viruses. Grab Group do 
not accept liability for any errors or omissions in the contents of this 
email arises as a result of email transmission. All intellectual property 
rights in this email and attachments therein shall remain vested in Grab 
Group, unless otherwise provided by law.

**Comment by tautvilas** [comment]
What do you mean there is no way to set today's date? Can you describe your usecase in more detail? Thanks.

**Comment by vinodkumar8** [comment]
Sorry my bad..I think you by default use Default date so I can use current date sorry for the confusion. I will abort the pr.

**Comment by vinodkumar8** [comment]
Not able to abort, please abort the PR.

**Pull request closed without merging**
