### PR TITLE
Created pure JS example, fixing #45

### PR DESCRIPTION
**Pull request by jkomyno**
@tautvilas https://github.com/wix/react-native-calendars/pull/91 had some issues, so I have done the example again in pure JS. It seems that either `yarn` or `expo` sometimes need `yarn start -- --cache-clear` to install the correct deps. Npm 4 works completely fine though.

### CODE REVIEW

**Comment by tautvilas** [comment]
I have resolved my yarn issue. It was this bug: https://github.com/yarnpkg/yarn/issues/2515

I will review & merge this soon.

**Comment by tautvilas** [comment]
I get this error when doing `npm run ios` :(
screen shot 2017-07-20 at 18 11 29

**Comment by jkomyno** [comment]
I ain't getting that, I was able to get it working both in Android and iOS. Can you please try removing `node_modules` and use `npm` instead of `yarn`?
Have you cleared your cache (e.g. watchman, npm cache clear, rn packager)?

**Comment by sibelius** [comment]
this is a problem with react-native 

"react": "16.0.0-alpha.6",
    "react-native": "0.44.0",

try to remove `^` from package.json

**Comment by tautvilas** [comment]
using react native 0.44.0 with yarn gives me another error. npm with 45.1 works fine (no problem)
screen shot 2017-07-20 at 18 35 06

It seems that react-native-navigation example is more stable than default `react-native-create-app` solution with `reactive-navigation` :/

**Comment by jkomyno** [comment]
@sibelius, I have removed node_modules and have run `npm i` and didn't have any issue. Note that I'm using npm@4.0.3. However I can remoe the "^" from package.json, no problem.

@tautvilas With create-react-native-app you have a different way of upgrading/downgrading react-native version. Please take a look [here](https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md).

**Comment by tautvilas** [comment]
npm works for me too no problem, but I am not sure we can have example project that does not support yarn

**Comment by jkomyno** [comment]
@tautvilas you're actually right, maybe we should let the team behind `yarn` know that we're having this kind of unexpected behaviour. Imho this isn't related to create-react-native-app

**Comment by tautvilas** [comment]
Apparently doing the npm cache clean and rebooting computer solved the issue with AccesibilityInfo module :) however I noticed that `yarn link` does not work with expo. This makes it difficult to develop module (when I want to check changes that I do in realtime on example project). Does anybody know how this could be solved?

**Comment by slorber** [comment]
@tautvilas some other opensource projects (like RN Storybook) are using [Haul](https://github.com/callstack-io/haul) packager instead of Metro as it supports linking

Metro does not support linking which makes it hard to contribute to RN projects and also use tools like Lerna

**Comment by tautvilas** [comment]
Decided to stick with react-native-navigation for now

**Pull request closed without merging**
