### PR TITLE
Agenda View toggled opened/closed callback

### PR DESCRIPTION
**Pull request by dborstelmann**
We had a need to render content based off whether the calendar was opened or not.  This just adds a prop to have a callback function fire with the state of the calendar when it's toggled opened or closed.  Would love to get this merged asap because it's so small!  Thanks.

### CODE REVIEW

**Comment by v3yr0n** [comment]
It would be good to have this merged ASAP :)

**Comment by tautvilas** [comment]
Hi, could you change prop type to onCalendarToggled? for consistency with other event handling props

**Comment by dborstelmann** [comment]
@tautvilas Done!

@v3yr0n Thanks!

**Comment by v3yr0n** [comment]
@tautvilas can this be merged now? :)

**Comment by v3yr0n** [comment]
@tautvilas when can this be pushed to npm?

**Comment by tautvilas** [comment]
I think I pushed. Isn't this available in 1.9.3?

**Comment by v3yr0n** [comment]
Ups, sorry, it is :)

**Comment by v3yr0n** [comment]
@tautvilas i know that this question is not related with this issue, but open an issue just to ask this... Is there any way to collapse the calendar from the agenda, like when you click on the knob, but programatically?
Thanks!

**Comment by tautvilas** [comment]
you could try calling agenda.chooseDay

**Comment by v3yr0n** [comment]
@tautvilas thanks for helping. I did call chooseDay and it worked. 
For anyone interested: `this.agenda.chooseDay(this.agenda.state.selectedDay);`

**Pull request merged**
