### PR TITLE
Using React Fragment to avoid style issue

### PR DESCRIPTION
**Pull request by jungleyu**
Here's one case for me:
I add styles for container view, but with a View for GestureRecognizer, my style will mess up, if we use Fragment, there will be no side effect on container.

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@jungleyu Hi. Please add a description to explain the issue with using a View vs. Fregment here?

**Comment by jungleyu** [comment]
> @jungleyu Hi. Please add a description to explain the issue with using a View vs. Fregment here?

sure

**Comment by jungleyu** [comment]
@Inbal-Tish While I'm trying to set the width of the calendar to "100%", it's not working.

**Comment by jungleyu** [comment]
image!


Expected:
[image](https://user-images.githubusercontent.com/6914315/157392901-700c4a06-2c12-4c0d-baaf-ea8619fe90bf.jpeg)

**Comment by Inbal-Tish** [comment]
@jungleyu How do you pass the width to the calendar? Are you not using the 'style' prop? Can you please add a code snippet?

**Comment by jungleyu** [comment]
@Inbal-Tish I'm using style={width: "100%"}, but worked with a fixed number, I thought that was caused by the View wrapper as I mentioned.
<GestureComponent> <-- This View layer do have side effect 
   <View style={props.style}></View>
</GestureComponent>

**Pull request closed without merging**
