### PR TITLE
Types mismatch

### PR DESCRIPTION
**Pull request by bmatasar**
`CalendarList.current` should be `string`, not `XDate`.
If I create an `<Agenda selected="2021-12-13" />` or `<Calendar current="2021-12-13" />`, I get the error:

> Warning: Failed prop type: Invalid prop `current` of type `object` supplied to `CalendarList`, expected `string`.

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@bmatasar Please see latest version

**Comment by bmatasar** [comment]
Tish, you need one more change to make it work. I rolled back the one already fixed.

**Comment by bmatasar** [comment]
Without this fix, it shows warnings in the case  `<Agenda selected="2021-12-13" />`.

**Comment by bmatasar** [comment]
It is already included in #1721

**Comment by Inbal-Tish** [comment]
@bmatasar Hi. Yes, I'm working on a type fix for the component. Thanks for the PR anyway!!!

**Pull request closed without merging**
