### PR TITLE
implemented custom style on Calendar type: period

### PR DESCRIPTION
**Pull request by maforn**
implemented custom container and text style on Calendar, markingType: period.
Is now possible to customize text and container style of each day of Calendar markingType={'period'} by adding to a day in markedDates customTextStyle={} and/or customContainerStyle={}.

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@maforn Can you please specify what are the customizations you trying to add here? Some screenshots will be of help.

**Comment by maforn** [comment]
@Inbal-Tish I would like to use custom text and container style in a calendar with markingType period.
Calendar
CalendarCode1
CalendarCode2

**Comment by Inbal-Tish** [comment]
@maforn Hi. I was wondering, why you're not using `markingType={'custom'}` for your customizations? Why add it to the Day type period?

**Comment by maforn** [comment]
> @maforn Hi. I was wondering, why you're not using `markingType={'custom'}` for your customizations? Why add it to the Day type period?

Hi. I actually cannot use `markingType={'custom'}` because it hasn't got centrals stripes between days, which are a prerogative of `markingType={'period'}`.

**Comment by Inbal-Tish** [comment]
@maforn Hi. Can you please add an example for this use in the Calendars screen in the example app so I can understand better what you're trying to achieve?

**Comment by phasjim** [comment]
Hello, I've been looking for the solution and I think this should work. 👍 
It seems like other people are also looking for this fix in this issue - https://github.com/wix/react-native-calendars/issues/1005

**Comment by phasjim** [comment]
@Inbal-Tish I'll add an example on the Calendars screen right now to show what we are trying to achieve

**Comment by phasjim** [comment]
@Inbal-Tish I can add an example of this usage in the app portion right now so we can get this merged in

**Comment by maforn** [comment]
Yeah, sorry I could not add any example because I do not have anymore the project (it was not mine).
Thank you @phasjim for adding one. I hope this solution will help someone.

**Comment by chenei** [comment]
Thanks @maforn for your contribution.
I added an example:
https://github.com/wix/react-native-calendars/pull/1176

**Comment by phasjim** [comment]
I didn't end up adding one because my computer couldn't get the react-native-app demo to work ut props to @chenei 👏  Thank you!

**Comment by sirus-max** [comment]
Hi @maforn ,
when i copied the example code and added bottomleft radius in it,  only the right side radii are working and not the left ones, 
Vice versa for the starting day.

```
{
        endingDay: true,
        color: '#50cebb',
        textColor: 'white',
        customContainerStyle: {
          borderTopRightRadius: 10,
          borderBottomRightRadius: 5,
          borderBottomLeftRadius: 5,
        },
   };
      
  ```

**Pull request merged**
