### PR TITLE
Fix: 'renderArrow' prop not being forwarded in 'CalendarListItem'

### PR DESCRIPTION
**Pull request by olfek**

### CODE REVIEW

**Comment by olfek** [comment]
Hello, 

It is likely this fork and its changes will be removed very soon for reasons beyond my control, I recommend that you merge these changes at your earliest convenience.

Thank you.

**Comment by olfek** [comment]
@tautvilas ...

**Comment by olfek** [comment]
@tautvilas Hello, several months have now passed, could you please take a look at this MR.

**Comment by olfek** [comment]
@Inbal-Tish ...

**Comment by BoKKeR** [comment]
I am also waiting for this to get merged.

**Comment by olfek** [comment]
The changes in this PR have been implemented in #609 which also includes the changes in [this commit](https://github.com/wix/react-native-calendars/pull/631/commits/2bbf2401786465efac933ef2ba2d249136c42219) from my other PR.

Closing this PR as it is now redundant.

**Pull request closed without merging**
