### PR TITLE
Add todayBackgroundColor in day components

### PR DESCRIPTION
**Pull request by christophehurpeau**
This PR gives more flexibility to style today container. It adds a new todayBackgroundColor:

```jsx
<CalendarList
  theme={{
    todayBackgroundColor: 'blue',
  }}
/>
```

but also allows more customisations:

```jsx
<CalendarList
  theme={{
    'stylesheet.day.basic': {
      today: {
        backgroundColor: 'blue',
        borderRadius: 5,
      }
    }
  }}
/>
```

### CODE REVIEW

**Comment by tautvilas** [comment]
This won't break backwards compatibility, right? Also is it ok to use undefined as a color?

**Comment by christophehurpeau** [comment]
Thanks for looking into this !
There are no break backwards compatibility, and react-native ignores undefined in style.

**Comment by christophehurpeau** [comment]
@tautvilas hello ! do you think you'll have some time to look at this again ?

**Comment by christophehurpeau** [comment]
Thank you !

**Pull request merged**
