### PR TITLE
Agenda: allow custom markedDates

### PR DESCRIPTION
**Pull request by slorber**
current markedDates=items default setting is not flexible enough for my usecase which if to mark the date only if one row of the day match a predicate

### CODE REVIEW

**Comment by tuanmai** [comment]
👍 for this PR. Please consider to merge this 😄

**Comment by tuanmai** [comment]
@slorber I think you should update the README too.

**Comment by slorber** [comment]
I've added it to readme example

**Comment by tautvilas** [comment]
Thanks for PR. also will add markingType prop possible for agenda, otherwise this feature would not be complete

**Pull request merged**
