### PR TITLE
Drag calendar list back up via the knob

### PR DESCRIPTION
**Pull request by amieczko**
Extended the drag area for the knob to the entire view width. Added ability to close agenda view by drag.

### CODE REVIEW

**Comment by JordanProtin** [comment]
Hi ! This feature will be part of the next release ?
Thk's

**Comment by ahtesham-shah** [comment]
I am using version 1.194.0 but not seeing knob to close agenda calendar how to do it.

**Comment by Inbal-Tish** [comment]
@amieczko Hi. Why are there changes to the native files and package.json in this PR. Can you please clean it so we can review the relevant changes only? Thanks!

**Comment by appinteractive** [comment]
What happend to that pr???

**Comment by Inbal-Tish** [comment]
@amieczko Closing this PR due to inactivity. Please open a new one if you will like me to review it. Thanks!

**Pull request closed without merging**
