### PR TITLE
Agenda - Added ability to hide the calendar part of the Agenda component

### PR DESCRIPTION
**Pull request by ashok3**
This change adds the option to disable/hide the calendar on top of the Agenda component.

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@ashok3 Thank you for the PR. Can you please remove the formatting so I can review the relevant changes?

**Comment by ashok3** [comment]
@Inbal-Tish - thanks for your reply. The formatting what are you referring to exactly? If you're talking about ESLint issues, they're already fixed in this commit on this PR: https://github.com/wix/react-native-calendars/pull/2139/commits/b6bc217b462c3a053498bd058440c77eed27267f and i think it passed all checks.

Let me know!

Also, we ended up using this and have a fully working version of this library in a soon to be production app now. Using the update here in this PR solves the issue we were seeing also here: https://github.com/wix/react-native-calendars/issues/2138 which seems to be a pretty critical issue. We almost didn't use the library. It seems like having this Calendar part on the Agenda causes the rendering issue which leads to that performance problem on latest versions of React Native. Just hiding it like we do in this PR seems to "fix" that or avoid the additional renders which works in our case. So it may be worth looking into why that's happening to solve that other issue.

**Comment by Inbal-Tish** [comment]
@ashok3 Hi. By "formatting" I mean all the line deletions, indentations, commas, and line breaks - all the formatting changes make the review cumbersome. I would like to see only the relevant changes and avoid changing the formatting according to each dev's config

**Comment by ashok3** [comment]
@Inbal-Tish - I've removed the formatting now, can you check? I think this causes the eslint checks to fail on GitHub though.

**Pull request closed without merging**
