### PR TITLE
refactor life cycles deprecated

### PR DESCRIPTION
**Pull request by avrcoelho**
Refactor life cycles componentWillMount and componentWillReceiveProps

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@avrcoelho Hi. Can you please resolve the conflicts?

**Comment by magrinj** [comment]
@avrcoelho Moving everything into `componentDidUpdate` isn't the right solution, if state need to be changed based on the props that need to be moved into `getDerivedStateFromProps`, and based on the previous state received by `componentDidUpdate` you can then trigger the needed internal functions. It's well explained right there: https://medium.com/hackernoon/replacing-componentwillreceiveprops-with-getderivedstatefromprops-c3956f7ce607

**Comment by avrcoelho** [comment]
should i resolve conflicts?

**Comment by Inbal-Tish** [comment]
@avrcoelho Thank you for the PR. Please check out PR #1356. Thanks!

**Pull request closed without merging**
