### PR TITLE
fix ExpandableCalendar expand/collapse animation

### PR DESCRIPTION
**Pull request by catherine-newman**
fix ExpandableCalendar expand/collapse animation - the bounce animation was not finishing

### CODE REVIEW

**Review by devic021 — APPROVED** [review]

**Comment by yuezonglun** [comment]
yes,My animation is still stuck

https://github.com/wix/react-native-calendars/assets/19408097/6e6f5871-039f-446b-99f6-23f616bf73d5

**Comment by CiprianDraghici** [comment]
Any idea when this PR will be merged? Thanks

**Comment by yuezonglun** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sergeyjsg** [comment]
Amazing work! Thanks! I was need to fork this repo in order to merge your changes.

**Comment by lyt8384** [comment]
Why hasn’t this PR been merged?
This problem has been bothering me.
Any idea when this PR will be merged? 
Thx~~

**Comment by demfabris** [comment]
thank you for this.
There's seems to be a little delay until you're able to expand/close again, not sure how to fix that

**Comment by yuezonglun** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request closed without merging**
