### PR TITLE
componentUpdater.ts uses propTypesMap instead of Component.propTypes

### PR DESCRIPTION
**Pull request by yairopro**
The purpose of this PR is to be able to use this library on the web.
If you try the library locally or on a  CodeSandbox, it works as a charm.
The problem is when CRA (`create-react-app`) builds a release. In its build process, CRA remove the components' `propTypes` for production.
Since the library uses `propTypes` to know what props to pass to lower components, all props can't pass down and it breaks in production (on web).

This PR comes to allow `componentUpdater.ts` to get components' `propTypes` by another way using a shared `Map` called `propTypesMap`. Each component set its own `propTypes` in the `propTypesMap`.

This pattern prevent CRA to remove `propTypes`.

### CODE REVIEW

**Comment by yairopro** [comment]
Made the PR on the `release` branch
https://github.com/wix/react-native-calendars/pull/1849

**Comment by yairopro** [comment]
Updated to master

**Comment by white-room** [comment]
What needs to happen to get this merged in? Would love to use this as a universal component!

**Comment by CheepyD** [comment]
When it will be merged in?

**Comment by dohomi** [comment]
any chance this getting merged?

**Comment by TNAJanssen** [comment]
Why was this never merged?

**Pull request closed without merging**
