### PR TITLE
Create pt-README.md

### PR DESCRIPTION
**Pull request by brunokiafuka**
Hi there, I've translated the readme to Portuguese.

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@brunokiafuka Hi. Thank you for the PR. Is this really necessary? English seems to be the standard so I'm not sure there is a need for translations...

**Comment by brunokiafuka** [comment]
@Inbal-Tish  Hi, the reason why I translated is that some Portuguese speakers struggle a bit with reading the docs in English and struggle to understand the content. But I also understand your point. 

🚀

**Comment by Inbal-Tish** [comment]
@brunokiafuka The all library is in English and also all communication. I'm closing this PR but thank you very much for this contribution. Hope to see you back here again :)

**Comment by brunokiafuka** [comment]
Thanks, @Inbal-Tish  :)

**Pull request closed without merging**
