### PR TITLE
Allow to customize calendar list inside the agenda

### PR DESCRIPTION
**Pull request by RimApp**
Hello,

First of all, thank you for this superb component!
The "CalendarList" component is not at all suitable for my needs.
I would like to be able to customize it with another component. So I created this PR.

Thank you.

### CODE REVIEW

**Comment by jeffthompson1971** [comment]
Can you please share a screenshot of  what this  change looks like?  Im very curious...

**Comment by RimApp** [comment]
Someone can review my PR please ?
@Inbal-Tish @ethanshar 
Thanks.

**Comment by Inbal-Tish** [comment]
@RimApp Hi. What are you not using `ExpandableCalendar` instead of the `Agenda`? Seems like a more appropriate component for your needs...

**Comment by RimApp** [comment]
> @RimApp Hi. Why are you not using `ExpandableCalendar` instead of the `Agenda`? Seems like a more appropriate component for your needs...

You mean `AgendaList` component ?

**Comment by Inbal-Tish** [comment]
@RimApp Hi. Take a look at this PR #1969 , this feature might be the one you need:

**Pull request closed without merging**
