### PR TITLE
use custom style in markingType 'multi-dot'

### PR DESCRIPTION
**Pull request by toonPt0473**
add custom style

### CODE REVIEW

**Comment by httpeace** [comment]
+1

**Comment by ccau1** [comment]
+1

**Comment by Inbal-Tish** [comment]
@toonPt0473 Hi. What is the issue you want to solve here? Why not use `markingType={'custom'}`?

**Comment by Thierno2sow** [comment]
hey @Inbal-Tish quick question on the  CalendarProvider is there a way to position the todayButton on the right bottom corner of the screen and not the left (react native)

**Comment by Inbal-Tish** [comment]
@Thierno2sow Use `todayButtonStyle`.

**Comment by Thierno2sow** [comment]
@Inbal-Tish thanks would something like this work 
    position: "absolute",
   
    right: 20,
    bottom: 0

**Pull request closed without merging**
