### PR TITLE
fix expandable calendar custom styling

### PR DESCRIPTION
**Pull request by timhubert**
For custom styling as in the other components

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@timhubert Hi. Thank you for the PR. Can you please explain why the other usage is not working and add a code snippet? I want to understand what is the reason for the code change.

**Comment by timhubert** [comment]
Hi @Inbal-Tish, the override works, but the form of how to override is different for this one component as it is for the other components.

E.g. In the other components and and according to [documentation](https://github.com/wix/react-native-calendars#advanced-styling):
```...(theme['stylesheet.day.basic'] || {})```
Stylesheet:
```'stylesheet.day.basic': { text: { ... } }```


Only this one component
`...(theme?.stylesheet?.expandable?.main || {})`
Stylesheet:
```stylesheet: { expandable: { main: { text: { ... } } } }```

It's not a big deal, but it's annoying.

**Comment by Inbal-Tish** [comment]
@timhubert Hi. When you use this style in the demo screen and run `npm run build:dev`, do you get a ts error?

**Comment by timhubert** [comment]
@Inbal-Tish No, I don't. Because of `// @ts-expect-error` (is exactly the same as in the other components)

**Comment by Inbal-Tish** [comment]
@timhubert Hi. I understand the usage is different here and it shouldn't, but this is a breaking change so I can't remove the old usage. We can keep both until the next major version...

**Comment by Seamus1989** [comment]
I want to override the day container - how do I do this? It flexes but II want to control its height and width which that the days in the calendar have no spacing between them?

**Comment by Inbal-Tish** [comment]
@Seamus1989 Hi. Add a screenshot with your design and we'll try to assist.

**Pull request closed without merging**
