### PR TITLE
feat(timeline): add testId to timeline

### PR DESCRIPTION
**Pull request by yakirza17**

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@yakirza17 Why did you remove the change in TimelineList?

**Comment by yakirza17** [comment]
@Inbal-Tish It will passed as part of _timelineProps

**Comment by Inbal-Tish** [comment]
> @Inbal-Tish It will passed as part of _timelineProps

You only need it on the Timeline component? You don't need another testID on the TimelineList component?

**Comment by yakirza17** [comment]
@Inbal-Tish no, the playable part is the scrollView inside the timeline, and the calendar component

**Review by Inbal-Tish — APPROVED** [review]

**Pull request merged**
