### PR TITLE
fix: this.scrollPad.scrollTo is not a function under expo

### PR DESCRIPTION
**Pull request by davidbiller**
Simulator Screen Shot - iPhone 11 Pro - 2020-06-14 at 16 30 00

### CODE REVIEW

**Comment by davidbiller** [comment]
Simulator Screen Shot - iPhone 11 Pro - 2020-06-14 at 16 30 00

**Comment by shamilovtim** [comment]
This needs attention please the plugin is broken in Expo with the error shown in this PR @emilisb @eilatc @chenei

**Comment by appinteractive** [comment]
@shamilovtim @davidbiller was this fixed? I get this here:

grafik

**Comment by emilisb** [comment]
Can you please give more info? It works for me on Expo 39.

**Comment by shamilovtim** [comment]
this was resolved

**Comment by appinteractive** [comment]
@emilisb @shamilovtim works for me also now with Expo 39 👍

**Comment by emilisb** [comment]
Awesome! I'm closing this PR.

**Pull request closed without merging**
