### PR TITLE
Disabled touch events for dates marked "disabled"

### PR DESCRIPTION
**Pull request by MyGuySi**
This PR addresses #149 with a potential solution. Thought I'd kick off the PR to discuss possible solutions.

I think a few users feel touch events should be disabled by default for dates which are marked "disabled". I agree that this is the best solution but I'm open to other suggestions such as an additional prop to toggle this behaviour.

### CODE REVIEW

**Comment by tautvilas** [comment]
thanks for PR

**Comment by kcfgl** [comment]
@tautvilas I have the latest version, and it looks like this is merged, but I can still click on dates and register the onDayPress which is making it a bit more challenging to ensure my markedDates is accurately reflected.  I'm using a CalendarList.  Here is the first part of the CalendarList ...

```
<CalendarList
                    onDayPress={this.onDayPress}
                    style={styles.calendar}
                    markedDates={this.state.markedDates}
                    disabledByDefault = {true}
```
I see that the dates change color to the disabled color when I add disabledByDefault = {true}.  But I can still click on any date. 

Thanks again for bringing the ability to disable by default, its going to be great!

**Comment by tautvilas** [comment]
Hi, maybe you can just filter disabled days in your onPress handler? I think there are cases when people want to display disabled dates and have them pressable too

**Comment by kcfgl** [comment]
@tautvilas Makes sense.  Thanks for letting me know this is the expected behavior.

**Pull request merged**
