### PR TITLE
Fixing typo in git clone

### PR DESCRIPTION
**Pull request by yemarnevets**

### CODE REVIEW

**Comment by tautvilas** [comment]
Hey, I think my version is correct.

This will not work for me: `git clone git@github.com/wix/react-native-calendars.git`

**Comment by yemarnevets** [comment]
Thanks for the reply! What OS are you using? I'm on a mac so that might be
why?

**Comment by tautvilas** [comment]
I'm on mac too. do you get error if you do `git clone git@github.com:wix/react-native-calendars.git`?

**Comment by yemarnevets** [comment]
It did earlier, but I can try again later.
It might've just been an unrecognised key error...

**Pull request closed without merging**
