### PR TITLE
Added monthComponent

### PR DESCRIPTION
**Pull request by thousight**
Added ability to customize the month and year component display

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@thousight Hi. What is the use for the custom month component? What would you like to customize? Screenshots will be of help

**Comment by thousight** [comment]
It is for adding more margins or making the month and year text size different. I left my original company already so I can't provide you screenshots.

**Comment by Inbal-Tish** [comment]
@thousight Hi. What is this 'monthComponent' you want to add to the CalendarHeader? Can you send me a screenshot of a use-case for this functionality?

**Comment by sykenrussel** [comment]
image
Hi I don't think I would get a reply from this, but an example screenshot would be a monthly charts like this one.

**Comment by Inbal-Tish** [comment]
@sykenrussel Why would you want it to be part of the Calendar component? You can use 'renderHeader' prop to customize the header if you need.

**Pull request closed without merging**
